language: cpp
os:
- osx
- linux
osx_image: xcode9.2
env:
- PYENV_VERSION='2.7.13' PYENV_VERSION_STRING='Python 2.7.13'
- PYENV_VERSION='3.5.5' PYENV_VERSION_STRING='Python 3.5.5'
- PYENV_VERSION='3.6.4' PYENV_VERSION_STRING='Python 3.6.4'
matrix:
  exclude:
    - os: linux
      env: PYENV_VERSION='2.7.13' PYENV_VERSION_STRING='Python 2.7.13'
    - os: linux
      env: PYENV_VERSION='3.5.5' PYENV_VERSION_STRING='Python 3.5.5'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libtcmalloc-minimal4
cache:
- pip
- directories:
  - "$HOME/.pyenv_cache"
before_install:
- |
  if [[ -n "$PYENV_VERSION" && "${TRAVIS_OS_NAME}" = 'osx' ]]; then
    wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
    source setup-pyenv.sh
    export PATH="${PYENV_ROOT}/bin:$PATH"
    deactivate
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    export CXX=g++-7
    cd /opt/pyenv && git pull origin master && cd -
    export PATH=/opt/pyenv/versions/${PYENV_VERSION}/bin:${PATH}
    pyenv install ${PYENV_VERSION}
    ls /opt/pyenv/versions/${PYENV_VERSION}/bin
    export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
  fi
- pyenv global ${PYENV_VERSION}
install:
- pip install --user numpy
- pip install --user scipy
- pip install --user matplotlib
- pip install --user sklearn
- pip install --user scikit-build
- pip install --user twine
- pip install --user wheel
script:
- python setup.py build
- python setup.py test
deploy:
  - provider: pypi
    user: classner
    password:
      secure: Wlcu0RuafPIIUcpy1cQcQ2nM4eT1DldoB1N46LcTTMQoWSgJFOfgZOkhSexUGN6SdynPtZxAQspU/rL91Y13dgOEq8Es+sANEB9AnXGz8G3hd22Z2nBkFFrvTJeQpS/HAoiRm9KZ9On5QrW9xbK9rwBe4zS7i4i+aIHBKqmoKvAwGuUaGz5a/dfClW5wMxbq4rsqCqYazBbFH98fiabKlGk6aX7JH9VrIEHoo+A2ZkGfYeZdmLuKcJktUbaqx9+yF9NPjKiBhMwUh8iS9maGIroRz5VGxf0Xm5VU7hb/Zja0dXKT9zpHIEysaRbH3kCXib9ytAIsH+JhFnF9bjO8RVG73lP47vNCRRDAv25/KK8gjebh4rpxceP9z94hCL+si0nzflwYx9ya8nNV39R6GmhQdw0xWzNuJp6vq2hYAvPNMFVB53umCDiMSs+UBCPkKhOM1ZaY8Sja8XUqUIwcgdneoKGjHyURSvemoFt+suzXYDL8V9W+0WhLGzGHoYNUeIpvnbaU1X9l3plxYXE+40OA2WM5nc9qctVZcm1Fpk4ORgCi4+BCniyBFFiiWcKEAmJLtS+KMbqH66uFmw5UngPwcxyG13DkZ15mL0EnIiXF/CFb5ki9Nxo5PbH4MN30Euc90CWWH6lSCISSfALCoBtJCh8UV4LUqZQF+o02WxY=
    skip_cleanup: true
    server: https://upload.pypi.org/legacy/
    distributions: bdist_wheel
    on:
      tags: true
      branches:
        only:
          - master
  - provider: pypi
    user: classner
    password:
      secure: Wlcu0RuafPIIUcpy1cQcQ2nM4eT1DldoB1N46LcTTMQoWSgJFOfgZOkhSexUGN6SdynPtZxAQspU/rL91Y13dgOEq8Es+sANEB9AnXGz8G3hd22Z2nBkFFrvTJeQpS/HAoiRm9KZ9On5QrW9xbK9rwBe4zS7i4i+aIHBKqmoKvAwGuUaGz5a/dfClW5wMxbq4rsqCqYazBbFH98fiabKlGk6aX7JH9VrIEHoo+A2ZkGfYeZdmLuKcJktUbaqx9+yF9NPjKiBhMwUh8iS9maGIroRz5VGxf0Xm5VU7hb/Zja0dXKT9zpHIEysaRbH3kCXib9ytAIsH+JhFnF9bjO8RVG73lP47vNCRRDAv25/KK8gjebh4rpxceP9z94hCL+si0nzflwYx9ya8nNV39R6GmhQdw0xWzNuJp6vq2hYAvPNMFVB53umCDiMSs+UBCPkKhOM1ZaY8Sja8XUqUIwcgdneoKGjHyURSvemoFt+suzXYDL8V9W+0WhLGzGHoYNUeIpvnbaU1X9l3plxYXE+40OA2WM5nc9qctVZcm1Fpk4ORgCi4+BCniyBFFiiWcKEAmJLtS+KMbqH66uFmw5UngPwcxyG13DkZ15mL0EnIiXF/CFb5ki9Nxo5PbH4MN30Euc90CWWH6lSCISSfALCoBtJCh8UV4LUqZQF+o02WxY=
    skip_cleanup: true
    server: https://upload.pypi.org/legacy/
    distributions: sdist
    on:
      tags: true
      condition: ${PYENV_VERSION} = "2.7.13" && "${TRAVIS_OS_NAME}" = "osx"
      branches:
        only:
          - master
